dashboard:
  usermanagment:
    label: Users
    uri:
    class: user
    order: 2
    pages:
      create:
        label: Add New
        module: users
        controller: management
        action: create
        route: default
      edit:
        label: All Users
        module: users
        controller: management
        action: index
        route: default
  statistic:
    pages:
      users:
        label: Users
        module: users
        controller: management
        action: stats
        route: default
default:
  userlogout:
    label: Logout
    route: logout
    module: users
    controller: login
    action: logout
  userlogin:
    label: Login
    route: login
    module: users
    controller: login
    action: index
  registration:
    label: Registration
    route: default
    module: users
    controller: register
    action: index
