dashboard:
  optionsmanagment:
    label: Options
    uri:
    class: list-alt
    order: 99
    pages:
      edit:
        label:Edit Options
        module:options
        controller:management
        action:index
        route:default