dashboard:
  blogmanagment:
    label: Blog
    uri:
    class: pencil
    order: 50
    pages:
      create:
        label: Add New Post
        module: blog
        controller: management
        action: create
        route: default
      edit:
        label: All Posts
        module: blog
        controller: management
        action: index
        route: default
  statistic:
    pages:
      blog:
        label: Blog
        module: blog
        controller: management
        action: stats
        route: default